name: M3U Birleştirici

on:
  push:
    branches:
      - main  # Değişiklik geldiği an otomatik başlar
  schedule:
    - cron: '0 2,14 * * *'  # Günde 2 kez otomatik başlar
  workflow_dispatch:        # İstediğinde elle (butonla) başlatmanı sağlar

permissions:
  contents: write

jobs:
  birlestir:
    runs-on: ubuntu-latest
    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0 

      - name: Python'u kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Bağımlılıkları kur
        run: pip install requests aiohttp

      - name: Eski Dosyaları ve Klasörleri Temizle
        run: |
          rm -rf nuvio_parcalari/
          rm -rf nuvio_dizi_parcalari/
          rm -f *.m3u

      - name: M3U Dosyalarını Oluştur
        run: |
          python m3u_sinema.py
          python m3u_dizi.py
          python m3u_tv.py
          python nuvio_sinema.py
          python nuvio_dizi.py  # <-- Dizi parçalayıcı buraya eklendi

      - name: Değişiklikleri commitle ve pusha gönder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Tüm parçalanmış klasörleri ve ana m3u'ları ekle
          git add nuvio_parcalari/
          git add nuvio_dizi_parcalari/
          git add *.m3u
          
          git add -u
          
          git add kayit_json_sinema/ || true
          git add kayit_json_dizi/ || true
          git add kayit_json_nuvio/ || true
          
          if git diff --staged --quiet; then
            echo "Değişiklik yok."
          else
            git commit -m "Sinema ve Dizi harf bazlı klasörleme yapıldı"
            git pull --rebase origin main
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
            git push origin main
          fi
